"""Search module for grid-based parameter optimization."""
from __future__ import annotations

from batchmatch.search.config import (
    AP,
    AxisGroup,
    DEFAULT_ORDER,
    GridAP,
    IterationOrder,
    AngleRange,
    ScaleRange,
    SearchParams,
    ShearRange,
    grid_for_rank,
    make_angle_predicate,
    make_scale_predicate,
    make_shear_predicate,
    ExhaustiveSearchConfig,
    PredicateConfig,
    SearchGridConfig,
)
from batchmatch.search.iterator import (
    IteratorStats,
    ProgressTracker,
    WarpParamIterator,
    iter_warp_params,
    make_search_progress,
)
from batchmatch.search.exhaustive import (
    ExhaustiveWarpSearch,
    build_moving_pipeline,
    build_reference_pipeline,
    compile_search,
)
from batchmatch.search.product import (
    ApplySearchResultStage,
    ApplyToIndexStage,
    ProductCropStage,
    ProductPipelineConfig,
    build_product_pipeline,
)
from batchmatch.search.transform import RegistrationTransform

__all__ = [
    "AP",
    "AxisGroup",
    "DEFAULT_ORDER",
    "GridAP",
    "IterationOrder",
    "AngleRange",
    "ScaleRange",
    "SearchParams",
    "ShearRange",
    "make_angle_predicate",
    "make_scale_predicate",
    "make_shear_predicate",
    "grid_for_rank",
    "PredicateConfig",
    "SearchGridConfig",
    "WarpParamIterator",
    "iter_warp_params",
    "IteratorStats",
    "ProgressTracker",
    "make_search_progress",
    "ExhaustiveSearchConfig",
    "ExhaustiveWarpSearch",
    "build_moving_pipeline",
    "build_reference_pipeline",
    "compile_search",
    "ApplySearchResultStage",
    "ApplyToIndexStage",
    "ProductCropStage",
    "ProductPipelineConfig",
    "build_product_pipeline",
    "RegistrationTransform",
]

try:
    from batchmatch.search.mpi import (
        InconsistentInputsError,
        MPISearchError,
        MPIExhaustiveSearchConfig,
        validate_inputs_consistent,
        serialize_search_result,
        deserialize_search_result,
        serialize_search_result_gpu,
        deserialize_search_result_gpu,
        merge_top_k_results,
        gather_results,
        allgather_results,
        gather_results_gpu,
        allgather_results_gpu,
        reduce_top_k,
        allreduce_top_k,
        reduce_top_k_gpu,
        allreduce_top_k_gpu,
        is_cuda_aware_mpi,
        MPIExhaustiveWarpSearch,
        mpi_exhaustive_search,
    )

    __all__.extend([
        "InconsistentInputsError",
        "MPISearchError",
        "MPIExhaustiveSearchConfig",
        "validate_inputs_consistent",
        "serialize_search_result",
        "deserialize_search_result",
        "serialize_search_result_gpu",
        "deserialize_search_result_gpu",
        "merge_top_k_results",
        "gather_results",
        "allgather_results",
        "gather_results_gpu",
        "allgather_results_gpu",
        "reduce_top_k",
        "allreduce_top_k",
        "reduce_top_k_gpu",
        "reduce_top_k_gpu",
        "allreduce_top_k_gpu",
        "is_cuda_aware_mpi",
        "MPIExhaustiveWarpSearch",
        "mpi_exhaustive_search",
    ])
except ImportError:
    pass
