from __future__ import annotations

from .base import (
    ImageMetric,
    ImageMetricEntry,
    ImageMetricSpec,
    register_image_metric,
    build_image_metric,
    available_image_metrics,
)
from .functions import (
    mse,
    mae,
    cross_correlation,
    local_cross_correlation,
    normalized_gradient_fields,
    soft_mutual_information,
    soft_nmi,
    mutual_information,
    nmi,
    prepare_metric_mask,
    combine_detail_masks,
)
from .metrics import (
    MeanSquaredErrorMetric,
    MeanAbsoluteErrorMetric,
    NormalizedCrossCorrelationMetric,
    LocalNormalizedCrossCorrelationMetric,
    NormalizedGradientFieldsMetric,
    DifferentiableMutualInformationMetric,
    DifferentiableNormalizedMutualInformationMetric,
    MutualInformationMetric,
    NormalizedMutualInformationMetric,
)

__all__ = [
    "ImageMetric",
    "ImageMetricEntry",
    "ImageMetricSpec",
    "register_image_metric",
    "build_image_metric",
    "available_image_metrics",
    "mse",
    "mae",
    "cross_correlation",
    "local_cross_correlation",
    "normalized_gradient_fields",
    "soft_mutual_information",
    "soft_nmi",
    "mutual_information",
    "nmi",
    "prepare_metric_mask",
    "combine_detail_masks",
    "MeanSquaredErrorMetric",
    "MeanAbsoluteErrorMetric",
    "NormalizedCrossCorrelationMetric",
    "LocalNormalizedCrossCorrelationMetric",
    "NormalizedGradientFieldsMetric",
    "DifferentiableMutualInformationMetric",
    "DifferentiableNormalizedMutualInformationMetric",
    "MutualInformationMetric",
    "NormalizedMutualInformationMetric",
]
