"""Visualisation: rendering, galleries, overlays, and registration previews."""
from .config import (
    ChannelSelection,
    DisplaySpec,
    ImageViewSpec,
    GallerySpec,
    GradientViewSpec,
    GradientGallerySpec,
    MaskViewSpec,
    MaskOverlaySpec,
    OverlaySpec,
    EdgeOverlaySpec,
    CheckerboardSpec,
    QuadAnnotationSpec,
    PointAnnotationSpec,
    BoxAnnotationSpec,
)

from .display import (
    show_image,
    show_channels,
    show_tensor,
    show_images,
    show_detail,
    show_gradient,
    show_gradients,
    show_gradient_hsv,
    show_mask,
    show_mask_overlay,
    show_comparison,
    show_annotated,
)

from .render import (
    normalize_minmax,
    normalize_percentile,
    normalize_symmetric,
    normalize_for_display,
    prepare_for_display,
    apply_gamma,
    apply_tint,
    to_rgb,
    to_uint8,
    apply_colormap,
    blend_alpha,
    gradient_magnitude,
    gradient_orientation,
    gradient_to_rgb,
    orientation_to_rgb,
    mask_to_contour,
    mask_to_overlay,
    create_checkerboard_mask,
    draw_grid_lines,
    compute_edge_magnitude,
    select_channels,
    downsample_for_display,
)

from .composite import (
    render_overlay,
    render_edge_overlay,
    render_checkerboard,
    render_side_by_side,
)

from .gradient import (
    render_gradient_component,
    render_gradient_gallery,
    render_gradient_hsv,
    render_gradient_with_quiver,
    get_quiver_data,
    render_gradient_from_tensors,
)

from .mask import (
    render_mask,
    render_mask_overlay,
    render_mask_contour_overlay,
    render_mask_from_tensor,
)

from .annotate import (
    annotate_quads,
    annotate_boxes,
    annotate_points,
    annotate_from_detail,
    draw_line,
    draw_polygon,
    draw_circle,
)

from .gallery import (
    create_image_grid,
    render_detail_gallery,
    render_detail_components,
    render_batch_gallery,
    render_tensor_gallery,
    render_channel_gallery,
)


__all__ = [
    "ChannelSelection",
    "DisplaySpec",
    "ImageViewSpec",
    "GallerySpec",
    "GradientViewSpec",
    "GradientGallerySpec",
    "MaskViewSpec",
    "MaskOverlaySpec",
    "OverlaySpec",
    "EdgeOverlaySpec",
    "CheckerboardSpec",
    "QuadAnnotationSpec",
    "PointAnnotationSpec",
    "BoxAnnotationSpec",
    "show_image",
    "show_channels",
    "show_tensor",
    "show_images",
    "show_detail",
    "show_gradient",
    "show_gradients",
    "show_gradient_hsv",
    "show_mask",
    "show_mask_overlay",
    "show_comparison",
    "show_annotated",
    "normalize_minmax",
    "normalize_percentile",
    "normalize_symmetric",
    "normalize_for_display",
    "prepare_for_display",
    "apply_gamma",
    "apply_tint",
    "to_rgb",
    "to_uint8",
    "apply_colormap",
    "blend_alpha",
    "gradient_magnitude",
    "gradient_orientation",
    "gradient_to_rgb",
    "orientation_to_rgb",
    "mask_to_contour",
    "mask_to_overlay",
    "create_checkerboard_mask",
    "draw_grid_lines",
    "compute_edge_magnitude",
    "select_channels",
    "downsample_for_display",
    "render_overlay",
    "render_edge_overlay",
    "render_checkerboard",
    "render_side_by_side",
    "render_gradient_component",
    "render_gradient_gallery",
    "render_gradient_hsv",
    "render_gradient_with_quiver",
    "get_quiver_data",
    "render_gradient_from_tensors",
    "render_mask",
    "render_mask_overlay",
    "render_mask_contour_overlay",
    "render_mask_from_tensor",
    "annotate_quads",
    "annotate_boxes",
    "annotate_points",
    "annotate_from_detail",
    "draw_line",
    "draw_polygon",
    "draw_circle",
    "create_image_grid",
    "render_detail_gallery",
    "render_detail_components",
    "render_batch_gallery",
    "render_tensor_gallery",
    "render_channel_gallery",
]
